<?php
$mv_text = [
	'h1'=>'Geothermal Power Generation',
];

set_query_var('mv_text', $mv_text);
get_template_part('include/mv');
?>

<?php get_template_part( '/include/breadcrumb' ); // パンくず ?>

<div class="l-content">
	<div class="m-box">
		<p class="m-round m-titleH3 m-sectionLarge tac"><span>Geothermal Energy <br>
		The Power Generation Method <br>
		Utilizing the Abundant Resources of Japan</span></p>

		<div class="m-sectionMega">
			<h2 class="m-titleH2">What is Geothermal Power Generation?</h2>
			<p class="m-txt m-sectionSmall tac sptal">It is a power generation method using hot water and steam produced by underground magma.</p>
		</div>

		<div class="m-sectionMega">
			<h2 class="m-titleH2">Flash Steam Power Generation</h2>

			<!-- FLASH BEGIN -->
			<div class="p-flash m-sectionMedium">
				<p><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_geothermal_power_en.gif" alt="Flash Steam Power Generation"></p>
				<p class="m-txtSmall mt10 nosp">※Mouseover the images to show a explanation</p>

				<ul class="m-hover-area nosp">
					<li class="p-flash-area-serparator"></li>
					<li class="p-flash-area-turbin"></li>
					<li class="p-flash-area-condenser"></li>
					<li class="p-flash-area-cooling"></li>
				</ul>

				<ul class="m-hover-comment nosp">
					<li class="p-flash-comment-serparator m-hover-comment-up">Steam and hot <br>
					water separated.</li>
					<li class="p-flash-comment-turbin m-hover-comment-down">Steam turbine-driven generator <br> produces electricity.</li>
					<li class="p-flash-comment-condenser m-hover-comment-up">Steam condensation at low <br>
					condenser pressure improves the <br>power generation output.</li>
					<li class="p-flash-comment-cooling m-hover-comment-down">Cooling tower cools the warm <br>water from condenser to <br>obtain cold water. The cold <br>water is pumped back to <br>condenser for cooling. </li>
				</ul>
			</div>
			<!-- FLASH END -->

			<p class="m-txt m-sectionMedium tac sptal">The geothermal fluid is taken out of the ground, separated into steam and hot water, and the steam is used to generate electricity.</p>
		</div>

		<div class="m-sectionMega">
			<h2 class="m-titleH2">Binary Power Generation</h2>

			<div class="p-binary-gif m-sectionSmall">
				<p><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_binary_power_en.gif" alt="Binary power generation"></p>
				<p class="m-txtSmall mt10 nosp">※Mouseover the images to show a explanation</p>

				<ul class="m-hover-area nosp">
					<li class="p-binary-area-separate"></li>
					<li class="p-binary-area-create"></li>
					<li class="p-binary-area-lique"></li>
					<li class="p-binary-area-condenser"></li>
					<li class="p-binary-area-power"></li>
					<li class="p-binary-area-heat"></li>
				</ul>

				<ul class="m-hover-comment nosp">
					<li class="p-binary-comment-separate m-hover-comment-down">Steam and hot <br>
					water separated.</li>
					<li class="p-binary-comment-create m-hover-comment-up">Separated steam <br>
					transfers its heat to <br> generate hot water.</li>
					<li class="p-binary-comment-lique m-hover-comment-up">Pressurized Hot water <br>
						transfers its heat to the<br>
						working fluid and <br>
						vaporizes it.</li>
					<li class="p-binary-comment-condenser m-hover-comment-down">Vaporized working fluid rotates the <br>
						turbine. Turbine drives the generator <br> 
						to produce electricity. </li>
					<li class="p-binary-comment-power m-hover-comment-up">Condensation of working fluid at low <br>
						condenser pressure improves power <br>
						generation output. <br>
						The subcooled condensate is pumped <br>
						back to the evaporator.</li>
					<li class="p-binary-comment-heat m-hover-comment-up">Cooling tower cools the <br>
						warm water from the <br>
						condenser to obtain cold <br>
						water. The cold water is <br>
						pumped back to the <br>
						condenser for cooling. </li>
				</ul>

			</div>
			<p class="m-txt m-sectionMedium">The steam or hot water from the geothermal reservoir is used to vaporize a working fluid with lower boiling point. The vaporized working fluid then rotates a turbine to generate electricity. As the power is generated by a secondary working fluid, this method is called as Binary power generation.</p>
		</div>

		<div class="m-sectionMega">
			<h2 class="m-titleH2">Features of Binary Power Generation</h2>

			<ul class="p-binary m-sectionMedium">
				<li>
					<p><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_low_temperature.jpg" alt="低温度の蒸気・熱水で発電可能"></p>
					<div class="p-binary-content">
						<p class="p-binary-title">Power Generation with Low Temperature Steam / Hot Water</p>
						<p class="m-txt">Unlike flash power generation, with the use of lower boiling point working fluid, it is possible to utilize low temperature steam / hot water (&lt;150°C) for power generation.</p>
					</div>
				</li>
				<li>
					<p><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_exsiting_hotspring.jpg" alt="既存の温泉井戸を活用できる"></p>
					<div class="p-binary-content">
						<p class="p-binary-title">Existing Hot Spring Wells Can Be Used</p>
						<p class="m-txt">It is possible to utilize an existing hot spring well as it can generate power even with a low-temperature heat source. This  reduces the cost of drilling wells and shortens the construction period.</p>
					</div>
				</li>
			</ul>
		</div>

		<div class="m-sectionMega">
			<h3 class="m-titleH3 tac">IWATEC’s Geothermal Power Generation Scheme <br>Utilizing Existing Hot Spring Wells <br>Working in collaboration with local community</h3>

			<p class="m-sectionMedium tac"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_corporation_en.jpg" alt="IWATEC’s Geothermal Power Generation Scheme Utilizing Existing Hot Spring Wells Working in collaboration with local community"></p>
		</div>

		<div class="m-sectionMega">
			<h3 class="m-titleH3 tac">Uses of Hot Spring Well </h3>

			<ul class="p-intro m-sectionSmall">
				<li>
					<p class="p-intro-title"><span>01<em class="nosp">---</em></span>Direct utilization of the heat from hot spring wells</p>
					<div class="p-intro-thrown p-intro-content m-sectionLarge">
						<p class="p-intro-thrown-base"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_thrown_en.png" alt="Direct utilization of the heat from hot spring wells"></p>
						<p class="p-intro-thrown-base-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_spring_smoke03.png" alt="smoke"></p>

						<div class="p-intro-thrown-block">
							<p class="p-intro-thrown-pipe p-intro-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_pipe.png" alt="pipe"></p>
							<p class="p-intro-thrown-smoke p-intro-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_smoke.png" alt="smoke"></p>
						</div>

						<div class="p-intro-thrown-block">
							<p class="p-intro-thrown-generation p-intro-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_generation_en.png" alt="Used for power generation"></p>
						
							<p class="p-intro-thrown-gear p-intro-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_gear.png" alt="gear"></p>
							<p class="p-intro-thrown-bulb p-intro-deco"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_bulb.png" alt="light bulb"></p>
						</div>
					</div>
				</li>
				<li>
					<p class="p-intro-title"><span>02<em class="nosp">---</em></span>Cascade utilization of the heat from hot spring wells</p>
					<div class="p-intro-hotspring p-intro-content m-sectionLarge">
						<div class="p-intro-hotspring-block is-appear">
							<p class="p-intro-hotspring-block-base"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_hotspring_en.png" alt="Utilizing the energy of hot springs"></p>
							<span class="p-intro-hotspring-smoke p-intro-hotspring-smoke01"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_spring_smoke01.png" alt="smoke"></span>
							<span class="p-intro-hotspring-smoke p-intro-hotspring-smoke02"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_spring_smoke02.png" alt="smoke"></span>
							<span class="p-intro-hotspring-smoke p-intro-hotspring-smoke03"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_spring_smoke03.png" alt="smoke"></span>
						</div>

						<div class="p-intro-hotspring-block">
							<p class="p-intro-hotspring-block-base p-intro-hotspring-block-base-second"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_hotspring02_en.png" alt="Utilizing the energy of hot springs"></p>
							<span class="p-intro-hotspring-smoke p-intro-hotspring-smoke04"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_spring_smoke03.png" alt="smoke"></span>

							<p class="p-intro-hotspring-gear p-intro-hotspring-deco">
								<img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_gear.png" alt="gear">
							</p>

							<p class="p-intro-hotspring-bulb p-intro-hotspring-deco">
								<img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/icn_bulb.png" alt="light bulb">
							</p>

						</div>
					</div>
				</li>
			</ul>
		</div>
		
		<!-- MERIT BEGIN -->
		<div class="m-sectionMega">
			<h2 class="m-titleH2">Benefits of Geothermal Power Generation</h2>
			<ul class="m-merit m-sectionMedium animate-default-orderCover">
				<li class="is-matchHeightPC2">
					<p class="animate-default-order"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_stable.jpg" alt="Constant Power Generation"></p>
					<div class="m-merit-title-cover is-matchHeightPC">
						<p class="m-merit-title">Constant Power Generation</p>
					</div>
					<p class="m-txt">Electricity can be generated throughout the year, and is attracting attention as a base load power source.</p>
				</li>
				<li class="is-matchHeightPC2">
					<p class="animate-default-order"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_reused.jpg" alt="Reuse of Steam / Hot Water"></p>
					<div class="m-merit-title-cover is-matchHeightPC">
						<p class="m-merit-title">Reuse of Steam /<br> Hot Water</p>
					</div>
					<p class="m-txt">Steam / Hot water after generating power can be reused for bathing or greenhouse cultivation.</p>
				</li>
				<li class="is-matchHeightPC2">
					<p class="animate-default-order"><img src="<?php echo ASSETS_PATH; ?>/images/services/geothermal-power-generation/img_co2.jpg" alt="Low CO2 Emissions"></p>
					<div class="m-merit-title-cover is-matchHeightPC">
						<p class="m-merit-title">Low CO<span class="m-txtMini">2</span> Emissions</p>
					</div>
					<p class="m-txt">Derived from natural energy sources, and no fuel combustion to generate electricity, so it emits less carbon dioxide than thermal power plants.</p>
				</li>
			</ul>
		</div>
		<!-- MERIT END -->

	</div>
	<!-- SERVICE CONSULT BEGIN -->
	<div class="m-serviceConsult-cover">
		<div class="m-serviceConsult">
			<div class="m-serviceConsult-content">
				<p class="m-serviceConsult-title">Consultation About Geothermal Power Generation</p>

				<div class="m-serviceConsult-inner">
					<div class="m-serviceConsult-left">
						<div class="m-serviceConsult-box m-serviceConsult-box-leftTop">
							<p class="m-serviceConsult-box-txt">How much does it <br>
							cost?</p>
						</div>
						<div class="m-serviceConsult-box m-serviceConsult-box-leftBottom">
							<p class="m-serviceConsult-box-txt">Is it possible with <br>
							my hot spring?</p>
						</div>
					</div>
					<div class="m-serviceConsult-center tac">
						<p><img src="<?php echo ASSETS_PATH; ?>/images/common/img_consult_man.png" alt="Consultation About Geothermal Power Generation"></p>
						<p class="m-serviceConsult-center-deco"><img src="<?php echo ASSETS_PATH; ?>/images/common/img_consult_man_head.png" alt="head"></p>
					</div>
					<div class="m-serviceConsult-right">
						<div class="m-serviceConsult-box m-serviceConsult-box-rightTop">
							<p class="m-serviceConsult-box-txt">How much electricity <br>
							can be produced?</p>
						</div>
						<div class="m-serviceConsult-box m-serviceConsult-box-rightBottom">
							<p class="m-serviceConsult-box-txt">Is the construction <br>
							procedure difficult?</p>
						</div>
					</div>
				</div>

				<p class="m-serviceConsult-sub">Please contact us for business details, questions or concerns.</p>
			</div>
			<?php get_template_part('include/en/contact_info_en') ?>
		</div>
	</div>
	<!-- SERVICE CONSULT END -->
	

	
	
	<?php get_template_part('include/en/service_link_en') ?>
</div>
